appName: 'my first app'

server:
  type: simple
  applicationContextPath: /api/server/v1
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

swagger:
  resourcePackage: com.ze.dropwizard

logging:
  level: INFO
  appenders:
    - type: console
      threshold: INFO


database:
  # the name of your JDBC driver
  #org.postgresql.Driver
  #driverClass: org.sqlite.JDBC
  driverClass: org.postgresql.Driver

  # the username
  user: apple

  # the password
  password: apple

  # the JDBC URL
  #url: jdbc:sqlite:F:/oschina/intellijU/java/resource/devhelper.sqlite
  url: jdbc:postgresql://127.0.0.1:5432/postgres

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute